2022-03-08 23:38:17,014 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-08 23:38:17,015 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\manoe\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2022-03-08 23:38:17,016 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-08 23:38:17,211 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-08 23:38:17,425 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-08 23:38:17,636 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-08 23:38:17,852 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-08 23:38:21,063 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-08 23:38:21,063 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXGGZ8Sc6XqQMcDl3yZGB5RDcToNYCA8hQ1-TFDuAzCkaro5jDsF9YifnT-g8ZWhoH8hx4w/KbuCfNv9Vo/","api_path":"/challenge/AXGGZ8Sc6XqQMcDl3yZGB5RDcToNYCA8hQ1-TFDuAzCkaro5jDsF9YifnT-g8ZWhoH8hx4w/KbuCfNv9Vo/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-08 23:38:21,063 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-08 23:38:21,063 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-08 23:38:21,064 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
