2022-03-08 23:37:53,027 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-08 23:37:53,027 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\manoe\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2022-03-08 23:37:53,028 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-08 23:37:53,290 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-08 23:37:53,505 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-08 23:37:53,710 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-08 23:37:53,942 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-08 23:37:55,372 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-08 23:37:55,372 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXHLCT_eo8imxrabvJ3axGiRPaUI3B-7GHiFovbIobWQJqsNGlwWQqEAoWVjmmmRYBhBrHg/l0g1EGCfA7/","api_path":"/challenge/AXHLCT_eo8imxrabvJ3axGiRPaUI3B-7GHiFovbIobWQJqsNGlwWQqEAoWVjmmmRYBhBrHg/l0g1EGCfA7/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-08 23:37:55,372 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-08 23:37:55,372 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-08 23:37:55,373 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
